In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_excel("/Users/praavars/FSFM/Penalty Kick/data/real_data.xlsx")
df.head()

,Unnamed: 0,Country,player_id,player_name,Kicker_Foot,Kicker_Side,Goalie_Side,Outcome,goalkeer_name,goalkeeper_id,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,player_name.1,player_id.1,Unnamed: 23,goalkeer_name.1,goalkeeper_id.1
0,24/25,Portugal,1.0,Galeno,R,L,L,1.0,Andrew,1.0,...,NaN,NaN,NaN,NaN,NaN,Galeno,1.0,NaN,Andrew,1.0
1,24/25,Portugal,2.0,Namaso,R,L,R,1.0,Andrew,1.0,...,NaN,NaN,NaN,NaN,NaN,Namaso,2.0,NaN,Dani Figueira,2.0
2,24/25,Portugal,3.0,Safira,R,R,L,1.0,Dani Figueira,2.0,...,NaN,NaN,NaN,NaN,NaN,Safira,3.0,NaN,Ricardo Batista,3.0
3,24/25,Portugal,4.0,Reisinho,L,L,R,1.0,Ricardo Batista,3.0,...,NaN,NaN,NaN,NaN,NaN,Reisinho,4.0,NaN,Gabriel Batista,4.0
4,24/25,Portugal,1.0,Galeno,R,L,R,1.0,Gabriel Batista,4.0,...,NaN,NaN,NaN,NaN,NaN,Alan,5.0,NaN,Nico Mantl,5.0

In [4]:
df.shape

(482, 26)

In [5]:
df.columns

Index(['Unnamed: 0', 'Country', 'player_id', 'player_name', 'Kicker_Foot',
       'Kicker_Side', 'Goalie_Side', 'Outcome', 'goalkeer_name',
       'goalkeeper_id', 'Home_Goals', 'Away_Goals', 'Minute', 'Team_Type',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'player_name.1',
       'player_id.1', 'Unnamed: 23', 'goalkeer_name.1', 'goalkeeper_id.1'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482 entries, 0 to 481
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       482 non-null    object
 1   Country          482 non-null    object
 2   player_id        475 non-null    float64
 3   player_name      482 non-null    object
 4   Kicker_Foot      482 non-null    object
 5   Kicker_Side      482 non-null    object
 6   Goalie_Side      482 non-null    object
 7   Outcome          482 non-null    float64
 8   goalkeer_name    482 non-null    object
 9   goalkeeper_id    481 non-null    float64
 10  Home_Goals       482 non-null    int64
 11  Away_Goals       482 non-null    int64
 12  Minute           482 non-null    int64
 13  Team_Type        482 non-null    object
 14  Unnamed: 14      0 non-null      float64
 15  Unnamed: 15      0 non-null      float64
 16  Unnamed: 16      0 non-null      float64
 17  Unnamed: 17      0 non-null      float64
 18  Unnamed: 18      0 non-null      float64
 19  Unnamed: 19      0 non-null      float64
 20  Unnamed: 20      0 non-null      float64
 21  player_name.1    178 non-null    object
 22  player_id.1      178 non-null    float64
 23  Unnamed: 23      0 non-null      float64
 24  goalkeer_name.1  109 non-null    object
 25  goalkeeper_id.1  109 non-null    float64
dtypes: float64(13), int64(3), object(10)
memory usage: 98.0+ KB

In [7]:
df.isnull().sum() ##Missing values in each column

Unnamed: 0           0
Country              0
player_id            7
player_name          0
Kicker_Foot          0
Kicker_Side          0
Goalie_Side          0
Outcome              0
goalkeer_name        0
goalkeeper_id        1
Home_Goals           0
Away_Goals           0
Minute               0
Team_Type            0
Unnamed: 14        482
Unnamed: 15        482
Unnamed: 16        482
Unnamed: 17        482
Unnamed: 18        482
Unnamed: 19        482
Unnamed: 20        482
player_name.1      304
player_id.1        304
Unnamed: 23        482
goalkeer_name.1    373
goalkeeper_id.1    373
dtype: int64

In [8]:
df.nunique() ##Unique values in each column

Unnamed: 0           4
Country              4
player_id          178
player_name        180
Kicker_Foot          2
Kicker_Side          3
Goalie_Side          3
Outcome              9
goalkeer_name      110
goalkeeper_id      109
Home_Goals           6
Away_Goals           5
Minute              87
Team_Type            2
Unnamed: 14          0
Unnamed: 15          0
Unnamed: 16          0
Unnamed: 17          0
Unnamed: 18          0
Unnamed: 19          0
Unnamed: 20          0
player_name.1      178
player_id.1        178
Unnamed: 23          0
goalkeer_name.1    109
goalkeeper_id.1    109
dtype: int64

In [9]:
df['Kicker_Side'].value_counts()

Kicker_Side
L    229
R    199
C     54
Name: count, dtype: int64

In [10]:
df['Kicker_Foot'].value_counts()

Kicker_Foot
R    323
L    159
Name: count, dtype: int64

In [11]:
df['Goalie_Side'].value_counts()

Goalie_Side
L    252
R    218
C     12
Name: count, dtype: int64

In [12]:
df['Outcome'].value_counts()

Outcome
1.000000    401
0.000000     73
0.041667      2
0.000694      1
0.125694      1
0.042361      1
0.001389      1
0.126389      1
0.083333      1
Name: count, dtype: int64

In [13]:
df['Unnamed: 0'].value_counts()

Unnamed: 0
20/21    150
24/25    112
23/24    111
22/23    109
Name: count, dtype: int64

In [14]:
df[~df['Outcome'].isin([0, 1])] ##Shows value for which Outcome is neither 0 nor 1

,Unnamed: 0,Country,player_id,player_name,Kicker_Foot,Kicker_Side,Goalie_Side,Outcome,goalkeer_name,goalkeeper_id,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,player_name.1,player_id.1,Unnamed: 23,goalkeer_name.1,goalkeeper_id.1
314,22/23,Italy,140.0,Andrea Belotti,R,C,R,0.000694,Vanja Milinkovič-Savič,67.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,22/23,Italy,96.0,Teun Koopmeiners,L,R,R,0.125694,Guillermo Ochoa,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,22/23,Italy,127.0,Abdelhamid Sabiri,R,R,R,0.042361,Lukasz Skorupski,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
319,22/23,Italy,120.0,Luis Alberto,R,L,L,0.001389,Luigi Sepe,68.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,22/23,Italy,94.0,Dušan Vlahović,L,L,R,0.126389,Martin Turk,89.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
322,22/23,Italy,141.0,Bryan Cristante,R,R,L,0.041667,Marco Silvestri,64.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,22/23,Italy,142.0,Roberto Pereyra,R,L,L,0.083333,Rui Patrício,82.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
324,22/23,Italy,143.0,Arkadiusz Milik,L,L,L,0.041667,Lukasz Skorupski,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.loc[
    ~df['Outcome'].isin([0, 1]),
    [
        'Unnamed: 0',
        'Country',
        'player_name',
        'Kicker_Foot',
        'Kicker_Side',
        'Goalie_Side',
        'Outcome',
        'goalkeer_name',
        'Home_Goals',
        'Away_Goals',
        'Minute',
        'Team_Type'
    ]
]

,Unnamed: 0,Country,player_name,Kicker_Foot,Kicker_Side,Goalie_Side,Outcome,goalkeer_name,Home_Goals,Away_Goals,Minute,Team_Type
314,22/23,Italy,Andrea Belotti,R,C,R,0.000694,Vanja Milinkovič-Savič,0,1,90,H
316,22/23,Italy,Teun Koopmeiners,L,R,R,0.125694,Guillermo Ochoa,3,1,38,H
318,22/23,Italy,Abdelhamid Sabiri,R,R,R,0.042361,Lukasz Skorupski,1,1,71,H
319,22/23,Italy,Luis Alberto,R,L,L,0.001389,Luigi Sepe,0,2,90,A
321,22/23,Italy,Dušan Vlahović,L,L,R,0.126389,Martin Turk,3,2,69,H
322,22/23,Italy,Bryan Cristante,R,R,L,0.041667,Marco Silvestri,1,0,37,H
323,22/23,Italy,Roberto Pereyra,R,L,L,0.083333,Rui Patrício,2,0,69,A
324,22/23,Italy,Arkadiusz Milik,L,L,L,0.041667,Lukasz Skorupski,1,1,31,H

In [16]:
df.rename(columns={'Unnamed: 0': 'Season', 'goalkeer_name': "goalkeeper_name"}, inplace=True) ##Renaming columns

In [17]:
df_clean = df[df['Outcome'].isin([0, 1])].copy()
df_clean['Outcome'].value_counts()

Outcome
1.0    401
0.0     73
Name: count, dtype: int64

In [18]:
df_clean.shape

(474, 26)

In [19]:
df_clean.isnull().sum()

Season               0
Country              0
player_id            7
player_name          0
Kicker_Foot          0
Kicker_Side          0
Goalie_Side          0
Outcome              0
goalkeeper_name      0
goalkeeper_id        1
Home_Goals           0
Away_Goals           0
Minute               0
Team_Type            0
Unnamed: 14        474
Unnamed: 15        474
Unnamed: 16        474
Unnamed: 17        474
Unnamed: 18        474
Unnamed: 19        474
Unnamed: 20        474
player_name.1      296
player_id.1        296
Unnamed: 23        474
goalkeer_name.1    365
goalkeeper_id.1    365
dtype: int64

In [20]:
df_clean[['player_name.1', 'player_id.1', 'goalkeer_name.1', 'goalkeeper_id.1', 
          'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 23']].head(20)

,player_name.1,player_id.1,goalkeer_name.1,goalkeeper_id.1,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 23
0,Galeno,1.0,Andrew,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Namaso,2.0,Dani Figueira,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Safira,3.0,Ricardo Batista,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Reisinho,4.0,Gabriel Batista,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Alan,5.0,Nico Mantl,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Fujimoto,6.0,Simao,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Clayton,7.0,Kewin,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,M. Leonardo,8.0,Velho,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Ángel Di María,9.0,Lucas França,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Cassiano,10.0,Varela,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,G. Assunçao,11.0,Bruno Brigiido,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,T. Silva,12.0,Robles,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,R. Pinho,13.0,Matheus,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,R. Macedo,14.0,Patrick S.,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Bruma,15.0,Caio Seco,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,O. Aranda,16.0,Lazar,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,A. Marques,17.0,Cesar,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,G. Silva,18.0,Guillermo Ochoa,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Jason,19.0,Miszta,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Yalcin,20.0,Rui Silva,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
columns_to_drop = [
    'Unnamed: 14',
    'Unnamed: 15',
    'Unnamed: 16',
    'Unnamed: 17',
    'Unnamed: 18',
    'Unnamed: 19',
    'Unnamed: 20',
    'Unnamed: 23',
    'player_name.1',
    'player_id.1',
    'goalkeer_name.1',
    'goalkeeper_id.1'
]

df_clean = df_clean.drop(columns=columns_to_drop)

In [22]:
df_clean.shape

(474, 14)

In [23]:
df_clean.columns

Index(['Season', 'Country', 'player_id', 'player_name', 'Kicker_Foot',
       'Kicker_Side', 'Goalie_Side', 'Outcome', 'goalkeeper_name',
       'goalkeeper_id', 'Home_Goals', 'Away_Goals', 'Minute', 'Team_Type'],
      dtype='object')

In [24]:
df_clean.isnull().sum()

Season             0
Country            0
player_id          7
player_name        0
Kicker_Foot        0
Kicker_Side        0
Goalie_Side        0
Outcome            0
goalkeeper_name    0
goalkeeper_id      1
Home_Goals         0
Away_Goals         0
Minute             0
Team_Type          0
dtype: int64

In [25]:
df_clean = df_clean.drop(columns=["player_id", "goalkeeper_id"])

In [26]:
df_clean.isnull().sum()

Season             0
Country            0
player_name        0
Kicker_Foot        0
Kicker_Side        0
Goalie_Side        0
Outcome            0
goalkeeper_name    0
Home_Goals         0
Away_Goals         0
Minute             0
Team_Type          0
dtype: int64

In [27]:
columns_to_check = ["Season", "Country", "Kicker_Foot", "Kicker_Side", "Goalie_Side", "Outcome"]
for items in columns_to_check:
    print (f"Column name: {items}")
    print("-" * 30)
    print (df_clean[items].value_counts())

Column name: Season
------------------------------
Season
20/21    150
24/25    112
23/24    111
22/23    101
Name: count, dtype: int64
Column name: Country
------------------------------
Country
Italy       166
Portugal    116
England     107
Italy        85
Name: count, dtype: int64
Column name: Kicker_Foot
------------------------------
Kicker_Foot
R    318
L    156
Name: count, dtype: int64
Column name: Kicker_Side
------------------------------
Kicker_Side
L    225
R    196
C     53
Name: count, dtype: int64
Column name: Goalie_Side
------------------------------
Goalie_Side
L    248
R    214
C     12
Name: count, dtype: int64
Column name: Outcome
------------------------------
Outcome
1.0    401
0.0     73
Name: count, dtype: int64

In [28]:
for country in df_clean["Country"].unique():
    print(repr(country))

'Portugal'
'England'
'Italy '
'Italy'

In [29]:
df_clean["Country"] = df_clean["Country"].str.strip()
df_clean["Country"].value_counts()

Country
Italy       251
Portugal    116
England     107
Name: count, dtype: int64

In [30]:
columns_to_check = ["Season", "Country", "player_name", "Kicker_Foot", "Kicker_Side", "Goalie_Side", "Outcome", "goalkeeper_name", "Home_Goals", "Away_Goals", "Minute", "Team_Type"]
for items in columns_to_check:
    print (f"Column name: {items}")
    print("-" * 30)
    print (df_clean[items].value_counts())

Column name: Season
------------------------------
Season
20/21    150
24/25    112
23/24    111
22/23    101
Name: count, dtype: int64
Column name: Country
------------------------------
Country
Italy       251
Portugal    116
England     107
Name: count, dtype: int64
Column name: player_name
------------------------------
player_name
Domenico Berardi    16
Franck Kessié       13
Ciro Immobile       13
Gyokeres            12
João Pedro          10
                    ..
Cunha                1
Madueke              1
Olise                1
Morgan G.            1
Cristo               1
Name: count, Length: 178, dtype: int64
Column name: Kicker_Foot
------------------------------
Kicker_Foot
R    318
L    156
Name: count, dtype: int64
Column name: Kicker_Side
------------------------------
Kicker_Side
L    225
R    196
C     53
Name: count, dtype: int64
Column name: Goalie_Side
------------------------------
Goalie_Side
L    248
R    214
C     12
Name: count, dtype: int64
Column name: Outcome
------------------------------
Outcome
1.0    401
0.0     73
Name: count, dtype: int64
Column name: goalkeeper_name
------------------------------
goalkeeper_name
Emil Audero             16
Bartlomiej Dragowski    16
Juan Musso              15
Lukasz Skorupski        14
Vicario                 14
                        ..
Gianluca Pegolo          1
Sels                     1
Travers                  1
Ivo G.                   1
João Gonçalves           1
Name: count, Length: 110, dtype: int64
Column name: Home_Goals
------------------------------
Home_Goals
0    251
1    134
2     66
3     15
4      7
5      1
Name: count, dtype: int64
Column name: Away_Goals
------------------------------
Away_Goals
0    257
1    147
2     53
3     15
4      2
Name: count, dtype: int64
Column name: Minute
------------------------------
Minute
90    46
45    33
26    15
71    10
62     9
      ..
40     2
63     1
3      1
4      1
11     1
Name: count, Length: 87, dtype: int64
Column name: Team_Type
------------------------------
Team_Type
H    260
A    214
Name: count, dtype: int64

In [31]:
df_clean.to_csv("data/cleaned_penalty_data.csv", index=False)